Private-Event Pull request 1
sergiocortessat/Rails_Private_Events pull request #3
Opened 2021-04-05 15:40 UTC by sergiocortessat

Private events project.

It complies with the requirements. Users can Sign up and Sign In.
As well each user has the ability to create as many events as they want. Also, each user has the ability to attend to other users' events at will. 

Such project includes de proper associations, scopes, and tables to comply with users, events, and attendance to events

2021-04-05 16:22 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Nice work in this project. You managed to create a working app. I was able to authenticate, create events and attend events created by other users. Well done!
- [x] Make some changes to the readme file. I left comments with suggestions.

### Martin Afani
#### Slack: whiz25

2021-04-05 16:22 UTC, whiz25 commented on README.md
> +3. run the command ```rails db:migrate```
- Add instruction for installing webpack using `yarn` to get rid of the error: ` Webpacker::Manifest::MissingEntryError in Events#index`

2021-04-05 16:22 UTC, whiz25 commented on README.md
> +4. run the command ```rails console```
- Add command for running the rails server locally

2021-04-05 16:22 UTC, whiz25 commented on README.md
> +## Contributing
- This section should be towards the end of this page. Add it before the `Acknowledgements` section.

2021-04-06 07:56 UTC, sergiocortessat commented
Pull request 2

We have added all the requirements pointed by the TSE such as

- Built with moved to the bottom
- Command to install webpack using yarn added
- Command to access the rails server on localhost

2021-04-06 08:42 UTC, rindrajosia requested changes
Changes Required :red_circle:
To Highlight: :angel:

- Good readme file :+1: 
- Good pull reqest description :100: 

To Improve :factory_worker: (REQUIRED)

- [x] It will be perfect if you remove logic in your  partial files (_header.html.erb) and put it in your helpers. As a developer your job is to create quality code that solves your client’s problems. Quality has many aspects to it, including readability and maintainability. It is much easier to read code that is lean and skinny, as well as serving a single purpose. When you look at a CSS file, you know it’s for styling and giving your site personality and uniqueness. When you look at a JavaScript file, you know it handles the interactivity on the front-end for the person viewing the site. And the view file is responsible for the HTML.
- [x] It will be nice if you add files(.DS_Store, ... ) not related to your project in your .gitignore file as you don't need them. 

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

2021-04-06 12:48 UTC, sergiocortessat commented
Pull request 3

We have added the requested required changes to the project:

- The file inside /public/.DS.store has been added to the .gitignore
- The logic of _header.html.erb has been moved to its appropriate helper. The if statements are performed here and call for the method user_options.

2021-04-06 13:57 UTC, jubaan requested changes
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>
<!-- BEGIN Awesome work -->

<!-- END Awesome work  -->
</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>
<!-- BEGIN Review -->

- [ ] Not only you should add non-related files/directories to `.gitignore` but also remove them from the repository if they had been uploaded before adding them to gitignore.


<!-- END Review -->
</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>
<!-- BEGIN Optional and Comments -->

- [x] Nothing more to add.

<!-- END Optional and Comments -->
</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    <img src="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px"/>
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> <img src="https://www.pinclipart.com/picdir/big/130-1305924_rubber-ducky-clipart-eastern-iowa-duck-race-duck.png" width="18px" height="18px">... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

2021-04-06 14:32 UTC, sergiocortessat commented
Pull request 4

The file DS.store has been deleted from the repository as well as requested.

2021-04-06 18:01 UTC, jubaan requested changes
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>
<!-- BEGIN Awesome work -->

<!-- END Awesome work  -->
</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>
<!-- BEGIN Review -->

- [ ] I saw the change made, but apparently something happen because the file still exist in the root directory of the project. If you look at the repo the .DS_store file still appears in it.


<!-- END Review -->
</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>
<!-- BEGIN Optional and Comments -->

- [x] Nothing more to add.

<!-- END Optional and Comments -->
</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    <img src="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px"/>
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> <img src="https://www.pinclipart.com/picdir/big/130-1305924_rubber-ducky-clipart-eastern-iowa-duck-race-duck.png" width="18px" height="18px">... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

2021-04-06 18:20 UTC, nganifaith commented
Thank You for the review. 
DS_Store has been removed from the main directory.

2021-04-06 18:36 UTC, smcommits approved these changes
# Status: Approved :+1: 
## Hello, @sergiocortessat and @nganifaith! You have done a great job. The application appears to be remarkable. Nice work implementing the changes that previous TSEs pointed out. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck.

2021-04-06 18:50 UTC, merged